# Generated by Django 2.2.13 on 2020-09-06 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moviespider', '0002_auto_20200906_0318'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieTable',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('star', models.IntegerField()),
                ('review', models.CharField(max_length=600)),
            ],
        ),
    ]
