# Generated by Django 2.2.13 on 2020-09-06 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviespider', '0003_movietable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movietable',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='movietable',
            table='movietable',
        ),
    ]
